version: '3.7'

services:

  portfolio-app:
    container_name: portfolio-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/portfolio-app'
      - '/portfolio-app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true